# Generated by Django 3.2 on 2022-07-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_ebook_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='review',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=50),
        ),
    ]
