# Generated by Django 3.2 on 2022-07-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_ebook_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='review',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
