# Generated by Django 3.2 on 2022-07-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_ebook_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='user',
        ),
    ]
